### ISSUE TITLE
Implement the pivot heat map

### ISSUE THREAD

**Issue by petrvecera** [petrvecera/ChessEloApp#16]
http://examples.sencha.com/extjs/6.5.0/examples/kitchensink/?modern#d3-view-heatmap-pivot

**Comment by HonzaTuron** [comment]
#11

**Comment by petrvecera** [comment]
Heat map != pivot grid

**Comment by HonzaTuron** [comment]
Yeah you named it wrongly.

**Comment by petrvecera** [comment]
Implemented in https://github.com/petrvecera/ChessEloApp/pull/31 and https://github.com/petrvecera/ChessEloApp/pull/32
